use dataindranil;

CREATE TABLE EMPLOYEE2 (
    EMP_ID INT,
    ENAME VARCHAR(20),
    JOB_DESC VARCHAR(25),
    SALARY INT,
    HIRE_DATE DATE
);

INSERT INTO EMPLOYEE2 VALUES (1,'RAM','ADMIN',100000,'2024-02-02');
INSERT INTO EMPLOYEE2 VALUES (2,'george','MANAGER',200000,'2024-02-02');
INSERT INTO EMPLOYEE2 VALUES (3,'Aravind','SALES',300000,'2024-02-02');
INSERT INTO EMPLOYEE2 VALUES (4,'Nivetha','SALES',250000,'2024-02-02');
INSERT INTO EMPLOYEE2 VALUES (5,'Hussain','HR',350000,'2024-02-02');

SELECT * FROM EMPLOYEE2;

SELECT * FROM EMPLOYEE1 ORDER BY JOB_DESC;

-- AVERAGE SALARY FOR EACH DEPARTMENT
SELECT JOB_DESC,AVG(SALARY) FROM EMPLOYEE1 GROUP BY JOB_DESC;

SELECT JOB_DESC,count(EMP_ID) FROM EMPLOYEE1 GROUP BY JOB_DESC;


SELECT JOB_DESC,COUNT(EMP_ID) FROM EMPLOYEE GROUP BY JOB_DESC;


SELECT JOB_DESC,COUNT(EMP_ID)
FROM EMPLOYEE1
GROUP BY JOB_DESC
HAVING COUNT(EMP_ID)>1
ORDER BY JOB_DESC;

SELECT JOB_DESC,COUNT(EMP_ID)
FROM EMPLOYEE WHERE SALARY>400000
GROUP BY JOB_DESC
HAVING COUNT(EMP_ID)>1
ORDER BY JOB_DESC;

use dataindranil;

CREATE TABLE EMPLOYEE2 (
    EMP_ID INT,
    ENAME VARCHAR(20),
    JOB_DESC VARCHAR(25),
    SALARY INT,
    HIRE_DATE DATE
);

INSERT INTO EMPLOYEE2 VALUES (1,'RAM','ADMIN',100000,'2024-02-02');
INSERT INTO EMPLOYEE2 VALUES (2,'george','MANAGER',200000,'2024-02-02');
INSERT INTO EMPLOYEE2 VALUES (3,'Aravind','SALES',300000,'2024-02-02');
INSERT INTO EMPLOYEE2 VALUES (4,'Nivetha','SALES',250000,'2024-02-02');
INSERT INTO EMPLOYEE2 VALUES (5,'Hussain','HR',350000,'2024-02-02');

SELECT ENAME FROM Employee2 WHERE Salary < (SELECT AVG(Salary) FROM Employee);

CREATE TABLE departments9 (
    department_id INT PRIMARY KEY,
    department_name VARCHAR(50)
);
CREATE TABLE employees9 (
    employee_id INT PRIMARY KEY,
    employee_name VARCHAR(50),
    department_id INT,
    FOREIGN KEY (department_id) REFERENCES departments(department_id)
);

INSERT INTO departments9 (department_id, department_name) VALUES
(1, 'Sales'),
(2, 'Marketing'),
(3, 'HR');

INSERT INTO employees9 (employee_id, employee_name, department_id) VALUES
(101, 'Alice', 1),
(102, 'Bob', 1),
(103, 'Charlie', 2),
(104, 'Diana', 3);








